-- Seed content for the services catalog, portfolio, and testimonials.
-- Mirrors backend/internal/repository/memory/seed.go, which is used instead
-- of this data when DATABASE_URL is not configured. See
-- docs/PROJECT_OVERVIEW.md for why portfolio/testimonial entries are
-- original demonstration content (is_demo = true) rather than documented
-- outcomes for a real, named client engagement.

INSERT INTO services (id, slug, category, name, summary, description, capabilities, icon, sort_order) VALUES
('svc-product-engineering', 'product-engineering', 'Engineering', 'Product Engineering',
 'SaaS platforms, web applications, and enterprise software built to scale.',
 'We design and build software products end to end — from a first working version to a system that holds up under real usage. That includes SaaS platforms, internal enterprise tools, and the APIs that connect them to everything else.',
 ARRAY['SaaS product development','Web application engineering','Enterprise software','REST & GraphQL APIs','Systems integration'],
 'layers', 1),
('svc-mobile-engineering', 'mobile-engineering', 'Engineering', 'Mobile Engineering',
 'Native and cross-platform apps for Android and iOS.',
 'We build mobile apps that ship to both stores without doubling the engineering effort where that trade-off makes sense, and go fully native when performance or platform depth calls for it.',
 ARRAY['Native Android','Native iOS','Cross-platform (Flutter / React Native)','App Store & Play Store delivery','Offline-first architecture'],
 'smartphone', 2),
('svc-digital-experience', 'digital-experience', 'Design', 'Digital Experience',
 'UI/UX, e-commerce, and brand experiences designed to convert.',
 'Interfaces that are easy to use and consistent across every screen. We cover product design systems, marketing websites, and e-commerce experiences, with an eye on the metrics those experiences are actually meant to move.',
 ARRAY['UI/UX design','Design systems','E-commerce experiences','Brand identity','Conversion-focused web design'],
 'palette', 3),
('svc-ai-automation', 'ai-automation', 'Engineering', 'AI & Automation',
 'AI integrations and automation that remove manual work.',
 'We integrate large language models and automation into existing products and internal workflows — from retrieval-augmented assistants to background automation that removes repetitive manual work.',
 ARRAY['LLM & AI integrations','Retrieval-augmented generation','Workflow automation','Intelligent internal tools','Data-driven decisioning'],
 'sparkles', 4),
('svc-growth', 'growth', 'Growth', 'Growth',
 'Technical SEO, performance marketing, and conversion optimization.',
 'Growth work grounded in the same engineering rigor as the product itself — technical SEO foundations, performance marketing, and structured conversion testing rather than guesswork.',
 ARRAY['Technical SEO','Performance marketing','Conversion rate optimization','Analytics & attribution','Content strategy'],
 'trending-up', 5),
('svc-continuous-support', 'continuous-support', 'Support', 'Continuous Support',
 'Maintenance, monitoring, security, and performance tuning.',
 'Launch is a milestone, not a finish line. We keep applications monitored, patched, and performing well after go-live, with clear SLAs instead of ad hoc support requests.',
 ARRAY['Application maintenance','Uptime monitoring','Security patching','Performance tuning','SLA-backed support'],
 'shield-check', 6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO projects (id, slug, name, category, tagline, summary, challenge, strategy, design_notes, engineering, outcome, tech_stack, accent_color, is_demo, sort_order) VALUES
('prj-meridian-health', 'meridian-health', 'Meridian Health', 'saas', 'Care coordination for multi-site clinics',
 'A scheduling and dispatch platform for a multi-location healthcare network, replacing spreadsheets and phone dispatch with a real-time operations dashboard.',
 'Dispatch coordinators tracked bookings and staff availability across spreadsheets and phone calls, causing double-bookings and slow responses at peak hours.',
 'We scoped a phased rollout starting with the highest-volume location, prioritizing one source of truth for scheduling before layering on reporting.',
 'A dense, information-first dashboard built around the coordinator''s actual workflow, with clear status states, rather than a generic admin template.',
 'React front end, a Go API with WebSocket updates for live dispatch status, and PostgreSQL for scheduling data, deployed on managed cloud infrastructure.',
 'Coordinators moved from phone-based dispatch to a shared live board across all locations within the first rollout phase.',
 ARRAY['React','TypeScript','Go','PostgreSQL','WebSockets'], 'indigo', true, 1),
('prj-harvestlink', 'harvestlink', 'HarvestLink', 'web', 'A digital marketplace connecting growers and buyers',
 'A responsive marketplace website for agricultural producers to list produce and connect directly with commercial buyers.',
 'Growers relied on informal phone networks to sell produce, with no shared place to list availability or pricing.',
 'We designed a lightweight listing-and-inquiry model instead of a full transactional marketplace, matching how buyers and sellers actually negotiate.',
 'Clear produce listings with availability, region, and photos, optimized for low-bandwidth mobile browsing.',
 'A Next.js storefront with server-rendered listings for search visibility, a Go API for listings and inquiries, and PostgreSQL.',
 'Gave growers a searchable public presence and a structured inquiry pipeline in place of informal calls.',
 ARRAY['Next.js','Go','PostgreSQL','Tailwind CSS'], 'emerald', true, 2),
('prj-swiftaid', 'swiftaid', 'SwiftAid', 'mobile', 'On-demand emergency transport, dispatched in seconds',
 'Companion Android and iOS apps connecting patients with nearby ambulance partners, plus a partner app for drivers.',
 'Requesting emergency transport meant calling individual operators with no visibility into who was actually available nearby.',
 'We split the product into a requester app and a partner app from day one, since dispatch reliability depended on partner adoption as much as requester demand.',
 'A minimal, high-contrast UI designed for stressful, time-critical use — large tap targets, status always visible on screen.',
 'Flutter for a single mobile codebase across both apps, a Go backend for dispatch matching, and PostgreSQL for location-aware queries.',
 'Replaced ad hoc phone dispatch with an app-based request-and-match flow for both patients and transport partners.',
 ARRAY['Flutter','Go','PostgreSQL','Push Notifications'], 'rose', true, 3),
('prj-vantage-goods', 'vantage-goods', 'Vantage Goods', 'web', 'A storefront rebuild built for conversion',
 'A full storefront redesign and rebuild for a multi-category retailer, focused on checkout speed and mobile conversion.',
 'The existing storefront had a slow, multi-step checkout and no mobile optimization, with cart abandonment concentrated on mobile traffic.',
 'We prioritized checkout and product-page performance over a full catalog redesign, since analytics pointed to those two steps as the leak.',
 'A streamlined single-page checkout and simplified product imagery and layout to cut load time on mobile networks.',
 'A Next.js storefront, a Go order-processing API, PostgreSQL, and an integrated third-party payment gateway.',
 'Shipped a materially faster checkout flow and mobile experience; the client''s team continued iterating on the new foundation after launch.',
 ARRAY['Next.js','Go','PostgreSQL','Payments API'], 'amber', true, 4),
('prj-openhands', 'openhands', 'OpenHands', 'design', 'Brand and web presence for a community nonprofit',
 'Brand identity, logo, and website for a nonprofit focused on community welfare programs, designed to build donor and volunteer trust.',
 'The organization had meaningful on-the-ground impact but no coherent visual identity or web presence to communicate it to donors.',
 'We led with a brand identity pass before web design, so the site had a real visual language to build on instead of a generic template.',
 'A warm, editorial layout foregrounding program stories and transparent impact reporting over generic stock imagery.',
 'A statically generated site built for low-maintenance long-term hosting, with a simple content workflow for the nonprofit''s team.',
 'Gave the organization a consistent brand identity and a website they could point donors and partners to directly.',
 ARRAY['Next.js','Figma','Tailwind CSS'], 'teal', true, 5),
('prj-ledgerly', 'ledgerly', 'Ledgerly', 'marketing', 'Technical SEO and content strategy for a B2B tool',
 'A technical SEO overhaul and content strategy for a B2B financial tools provider, rebuilding organic visibility after a platform migration.',
 'A recent platform migration had broken canonical tags and internal linking, causing a sharp drop in organic search visibility.',
 'We fixed technical foundations first — crawlability, canonicals, structured data — before investing in new content.',
 'Restructured information architecture so high-intent pages were reachable within two clicks of the homepage.',
 'Server-rendered pages with proper metadata and schema.org markup, sitemap automation, and search-console monitoring.',
 'Restored technical health across the site and re-established a consistent publishing cadence for organic content.',
 ARRAY['Next.js','Schema.org','Search Console','Analytics'], 'violet', true, 6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO testimonials (id, quote, author, role, project_id, is_demo, sort_order) VALUES
('tst-meridian-health', 'The live dispatch board matches how our coordinators actually work — no more tracking availability across five phone lines.', 'Operations Lead', 'Regional healthcare network · Meridian Health case study', 'prj-meridian-health', true, 1),
('tst-harvestlink', 'We went from word-of-mouth sales to a searchable listing our buyers actually use.', 'Founder', 'Agricultural marketplace · HarvestLink case study', 'prj-harvestlink', true, 2),
('tst-swiftaid', 'Drivers adopted the partner app faster than we expected, because it respects how little time they have to look at a screen.', 'Fleet Coordinator', 'Emergency transport network · SwiftAid case study', 'prj-swiftaid', true, 3),
('tst-vantage-goods', 'Checkout finally feels as fast on a phone as it does on a laptop.', 'E-commerce Manager', 'Multi-category retailer · Vantage Goods case study', 'prj-vantage-goods', true, 4),
('tst-openhands', 'The new site gives donors something to point to. It finally looks like the organization we actually are.', 'Program Director', 'Community nonprofit · OpenHands case study', 'prj-openhands', true, 5),
('tst-ledgerly', 'Our organic traffic stopped bleeding out within the first month of the technical fixes landing.', 'Head of Marketing', 'B2B fintech tools provider · Ledgerly case study', 'prj-ledgerly', true, 6)
ON CONFLICT (id) DO NOTHING;
